name: GitHub Actions Demo
run-name: GitHub Actions Workflow new 22ğŸš€
on: 
 pull_request:
   branches:
     - main
   types: [closed]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github. }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Hello world
        run: 
          | 
            echo "Hello world from $GITHUB_BASE_REF"
            echo "Hello world from GITHUB_HEAD_REF"
        
      
